name: PR Build Check

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'assets/**'

permissions:
  contents: read

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          cache: true

      - name: Get Flutter version
        run: flutter --version

      - name: Get Flutter packages
        run: flutter pub get

      - name: Analyze Dart code
        run: flutter analyze

      - name: Build APKs
        run: |
          flutter build apk
          flutter build apk --split-per-abi

      - name: Build App Bundle
        run: flutter build appbundle