name: PR Build Check

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'assets/**'

permissions:
  contents: read

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.x'
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk --split-per-abi
      - run: flutter build appbundle