name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          all_but_latest: true

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.x'
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk --split-per-abi

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'philripd/anime-browser'
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Sign APKs
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'philripd/anime-browser'
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: build/app/outputs/flutter-apk
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Clean up build artifacts
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'philripd/anime-browser'
        run: |
          set -e

          mv build/app/outputs/flutter-apk/app.apk animebrowser-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum animebrowser-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV

          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk animebrowser-arm64-v8a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum animebrowser-arm64-v8a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV

          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk animebrowser-armeabi-v7a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum animebrowser-armeabi-v7a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV

          cp build/app/outputs/flutter-apk/app-x86_64-release.apk animebrowser-x86_64-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum animebrowser-x86-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_SHA=$sha" >> $GITHUB_ENV

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'philripd/anime-browser'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: Anime Browser ${{ env.VERSION_TAG }}
          body: |
            ---

            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | Universal | ${{ env.APK_UNIVERSAL_SHA }}
            | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }}
            | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }}
            | x86_64 | ${{ env.APK_X86_SHA }} |
          files: |
            animebrowser-${{ env.VERSION_TAG }}.apk
            animebrowser-arm64-v8a-${{ env.VERSION_TAG }}.apk
            animebrowser-armeabi-v7a-${{ env.VERSION_TAG }}.apk
            animebrowser-x86_64-${{ env.VERSION_TAG }}.apk
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}